name: contrastive
channels: 
  - defaults
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11.5
  - pip
  - ipykernel
  - matplotlib
  - tqdm
  - torchvision
  - torchaudio 
  - pytorch-cuda=12.1
  - lightning
  - scikit-image
  - pandas
  - pip:
    - pydicom
    - wandb
    - rich